# The minimum velocity that can be applied to the player upon punching.
minimum-punch-strength: 5

# The maximum velocity that can be applied to the player upon punching.
maximum-punch-strength: 20

# The vertical velocity applied to the player upon punching.
vertical-strength: 10