name: Punch
version: '${project.version}'
main: dev.caramel.punch.Punch
api-version: 1.18
authors: [ Caramel ]
description: Plugin to make players go up when they punch another player.
commands:
  punch:
    description: Simulate punching a player by yeeting them into the sky.
