name: Punch
version: '${project.version}'
main: dev.caramel.punch.Punch
api-version: 1.18
authors: [ Caramel ]
description: Get a punching stick to send enemies to another dimension.
commands:
  punch:
    description: Get a punching stick to send enemies to another dimension.
